name: Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check for existing labels
      id: check_labels
      uses: actions/github-script@v6
      with:
        script: |
          const issueLabels = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          return { hasNoLabels: issueLabels.data.length === 0 };

    - name: Add 'new issue' label
      if: steps.check_labels.outputs.hasNoLabels == 'true'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'new issue'
