name: Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Add 'new issue' label
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'new issue'
        repo: 'Nikita-FH/CodeSpaceTest'
