name: Label New Issues

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Check for existing labels
      id: check_labels
      uses: actions/github-script@v6
      with:
        script: |
          const issueLabels = await github.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          return issueLabels.data.length === 0;

    - name: Add 'new issue' label
      if: steps.check_labels.outputs.result == 'true'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: 'new issue'
        repo: 'Nikita-FH/CodeSpaceTest'
